apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.bmutziu.me"
webhooks:
- name: "pod-policy.bmutziu.me"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "default"
      name: "hdac"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVWFBOVEJ0NzZtZS9uOVU4UnY3WGZZdzRycVg0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tZbTExZEhwcGRTMWpZVEFlRncweU1UQXhNVEl3T0RNMk1qUmFGdzB5TWpBeApNVEl3T0RNMk1qUmFNQlV4RXpBUkJnTlZCQU1NQ21KdGRYUjZhWFV0WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERWY1TjM0Vkx0R0pVVjZxZzVHbHdNMSt6bk9LVG1EejhVcGF0RjBlNjUKN2ExdWtuamZwV204WHZWZHNMYXgwZFRFbVhWWEJNUU1QbWhKNG1qRkZ2YzMwaGpidk0wSUFBaXFZQ2VWYWFVZApRVlA4ZFdmTXIzTVpEaTNkRVZjdWVyZkcrNDVFREVQa3ByNjVzWE5oNC9FUXphRjM3ZHdsazAwYUlweGZlSGkyCmo2c2VlcVFEK0FRNmxJdDdrbldQRk8zcnlPUkxFSk82dXF2Mm5CQVFyeTBkcVRtZFJROXhNOVpmcnhucUc1OHcKc2FNb1dKWnJmSzRxYjRJNm9TV0tNQldzVE4rQTYwVzdocmxNMGxjaUUxZG9kMTZJajMzWjg3dnFBM05kOUEzVwpOb2JyUGRzOVhQSS9DeDQ5eDFiYVBzTHE3M09EOHV1VTRTMkFyRjNPbUlrSkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlJJRDJoNkVuM3pOWXV0UUk5TlRVSVhVaktqc2pBZkJnTlZIU01FR0RBV2dCUklEMmg2RW4zek5ZdXQKUUk5TlRVSVhVaktqc2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDeApPTHdKTS9DZkQwUXdRYXJ1RlNQZFZTVXprSGRtMEJJSTZOWlVPWjF6TGJIMjhlVWxSQW5tNXMxS3hoNTdlUmQ4CmZjelNsODRUcGpPNUtKd3BodU8rMGZjQUVTbDN6QjE4WmtFWFFSaUo0aU81OUwrcjNmd0E1VlRuV1lXemlVTk4KbEMvc0xNSWlIY0FVVUF0U2ltWkZCcjBhNDR4U0htQ2c5UVFSVk15azl6YXNqckJGZjFtM3dyL040VHRZQUpmcQpCZDVYRlVULy9ZeXFOVmd5T0Z3VnVjcnRkek16QXJEaGh4eUZhSDJNV1JsOExXbUltc2M5SFlEME5yL0R2bU5QCjM4aUJRKy9ydGdRZUM0OXN4ZjV6TG9KSi9RWC9ia05ad1dhM3ByWXJkMHhBVCtHVDdSQ0hOQXBwYlpVczBJMU0KL3Z4TmhWQTNyWmdnQnZlWlMvWlkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
